services:
  db:
    image: postgres:16 
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: filestorage
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  minio:
    image: quay.io/minio/minio:latest 
    container_name: minio
    ports:
      - "9000:9000" 
      - "9001:9001" 
    environment:
      MINIO_ROOT_USER: minioadmin 
      MINIO_ROOT_PASSWORD: minioadmin 
      MINIO_DEFAULT_BUCKETS: bucket 
    volumes:
      - minio_data:/data 
    command: server --console-address ":9001" /data

volumes:
  pgdata:
  minio_data:
